### ISSUE TITLE
rename folder core_ontology in object biography ontology

### ISSUE THREAD

**Issue by anja-gerber** [nfdi4objects/n4o-core-ontology#9]
We need to differentiate between the types of ontologies and datamodels being developed in N4O:
* N4O Core Ontology as connection to NFDI Core
* N4O Object data model as RDF-derivate of the minimal metadata set being developed in the consortia
* N4O Object data model for the object biographies

**Comment by nichtich** [comment]
I'd ignore [NFDIcore Ontology](https://ise-fizkarlsruhe.github.io/nfdicore/) and later map to its classes and properties when needed. A minimal metadata set is neither practical at the moment as long as there are no tools and workflows to check compliance with the metadata set (what is going to happen if some data does not use all of the required fields?). This leaves **the N4O Object data model for the object biographies** as an extension to CRM.

**Comment by nichtich** [comment]
The folder has been removed and the RDF file is in root directory. Older versions can be retrieved from git history.
